### ISSUE TITLE
界面不显示

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/Mua#3]
0.09版本，打开之后界面闪一下，然后就没了

任务栏图标还在，但是没窗口
![image](https://user-images.githubusercontent.com/18511905/133265104-70d6f46c-3845-48a7-8604-c8685a064cb6.png)

**Comment by LoveLoliii** [comment]
> 0.09版本，打开之后界面闪一下，然后就没了
> 
> 任务栏图标还在，但是没窗口
> ![image](https://user-images.githubusercontent.com/18511905/133265104-70d6f46c-3845-48a7-8604-c8685a064cb6.png)

try 0.1,1

**Comment by LoveLoliii** [comment]
fixed
